let shopItemsData = [
    {
      id: "americano12oz",
      name: "Americano",
      price: 55,
      desc: "A strong black coffee made with espresso and hot water.",
      img: "americano.jpg",
    },
    {
      id: "spanishLatte12oz",
      name: "Spanish Latte",
      price: 65,
      desc: "A rich espresso combined with steamed milk and a hint of caramel.",
      img: "spanish latte.jpg",
    },
    {
      id: "matchaEspresso12oz",
      name: "Matcha Espresso",
      price: 60,
      desc: "A blend of matcha and espresso with steamed milk.",
      img: "matcha espresso.jpg",
    },
    {
      id: "caramelMacchiato12oz",
      name: "Caramel Macchiato",
      price: 65,
      desc: "Espresso combined with steamed milk and topped with caramel syrup.",
      img: "iced caramel macchiato.jpg",
    },
    {
      id: "hazelnutMacchiato12oz",
      name: "Hazelnut Macchiato",
      price: 65,
      desc: "A sweet espresso with steamed milk and a hint of hazelnut flavor.",
      img: "hazelnut_macchiato.jpg",
    },
    {
      id: "almondLatte12oz",
      name: "Almond Latte",
      price: 60,
      desc: "A smooth blend of espresso, steamed milk, and almond flavor.",
      img: "almondl.jpg",
    },
    {
      id: "butterscotchLatte12oz",
      name: "Butterscotch Latte",
      price: 60,
      desc: "A delicious blend of espresso, steamed milk, and butterscotch syrup.",
      img: "butterscotch_latte.jpg",
    },
    {
      id: "mochaLatte12oz",
      name: "Mocha Latte",
      price: 60,
      desc: "A rich espresso mixed with steamed milk and chocolate syrup.",
      img: "mocha_latte.jpg",
    },
    {
      id: "javaChip16oz",
      name: "Java Chip",
      price: 89,
      desc: "A chocolatey frappe made with coffee, chocolate chips, and ice.",
      img: "javaF.jpg",
    },
    {
      id: "butterscotch16oz",
      name: "Butterscotch",
      price: 79,
      desc: "A smooth frappe with butterscotch flavor and ice.",
      img: "butterscotch.jpg",
    },
    {
      id: "almondFrappe16oz",
      name: "Almond Frappe",
      price: 79,
      desc: "A chilled frappe blended with almond flavor and ice.",
      img: "almondf.jpg",
    },
    {
      id: "hazelnutFrappe16oz",
      name: "Hazelnut Frappe",
      price: 79,
      desc: "A rich frappe with hazelnut flavor and ice.",
      img: "hazelnutf.jpg",
    },
    {
      id: "matchaFrappe16oz",
      name: "Matcha Frappe",
      price: 79,
      desc: "A refreshing frappe with matcha flavor and ice.",
      img: "matcha_frappe.jpg",
    },
    {
      id: "darkMochaFrappe16oz",
      name: "Dark Mocha Frappe",
      price: 79,
      desc: "A decadent dark chocolate frappe with ice.",
      img: "fpp.jpg",
    },

        {
            id: "okinawamlk01",
            name: "Okinawa Milk Tea",
            price: 39,
            desc: "A delicious milk tea with Okinawan sugar and creamy milk.",
            img: "images/okinawa.jpg",
        },
        {
            id: "wintermelon01",
            name: "Wintermelon Milk Tea",
            price: 39,
            desc: "A smooth and refreshing wintermelon milk tea.",
            img: "images/wintermt.jpg",
        },
        {
            id: "saltedcaramel01",
            name: "Salted Caramel Milk Tea",
            price: 39,
            desc: "Sweet and salty, the perfect balance of flavor.",
            img: "images/salted_caramel.jpg",
        },
        {
            id: "cookiescream01",
            name: "Cookies n' Cream Milk Tea",
            price: 39,
            desc: "A creamy and indulgent treat with crushed cookies.",
            img: "images/cookies_cream.jpg",
        },
        {
            id: "cheesecake01",
            name: "Cheesecake Milk Tea",
            price: 39,
            desc: "A rich milk tea flavor with the smooth taste of cheesecake.",
            img: "images/cheesecake.jpg",
        },
        {
            id: "taro01",
            name: "Taro Milk Tea",
            price: 140,
            desc: "A creamy and sweet taro milk tea.",
            img: "images/taro.jpg",
        },
        {
            id: "redvelvet01",
            name: "Red Velvet Milk Tea",
            price: 39,
            desc: "A luxurious red velvet flavored milk tea.",
            img: "images/red_velvet.jpg",
        },
        {
            id: "strawberry01",
            name: "Strawberry Milk Tea",
            price: 39,
            desc: "A fruity, sweet milk tea with the flavor of fresh strawberries.",
            img: "images/milk tea.jpg",
        },
        {
            id: "strawberryfruit01",
            name: "Strawberry Fruit Tea",
            price: 45,
            desc: "A refreshing fruit tea with the natural sweetness of strawberries.",
            img: "images/fruitteaa.jpg",
        },
        {
            id: "greenapplefruit01",
            name: "Green Apple Fruit Tea",
            price: 45,
            desc: "A tangy and crisp green apple fruit tea.",
            img: "images/fruitteaa.jpg",
        },
        {
            id: "lychee01",
            name: "Lychee Fruit Tea",
            price: 45,
            desc: "A tropical fruit tea with the exotic taste of lychee.",
            img: "images/fruitteaa.jpg",
        },
        {
            id: "lemon01",
            name: "Lemon Fruit Tea",
            price: 45,
            desc: "A zesty fruit tea with a burst of fresh lemon.",
            img: "images/fruitteaa.jpg",
        },
        {
            id: "strawberriescream01",
            name: "Strawberries and Cream",
            price: 65,
            desc: "A creamy and fruity drink with fresh strawberries.",
            img: "images/sc.jpg",
        },
        {
            id: "matchamilk01",
            name: "Matcha Milk",
            price: 70,
            desc: "A smooth, earthy matcha milk drink.",
            img: "images/noncoffe.jpg",
        },
        {
            id: "strawberrymatchamilk01",
            name: "Strawberry Matcha Milk",
            price: 80,
            desc: "A delicious fusion of strawberry and matcha milk.",
            img: "images/noncoffe.jpg",
        },
        {
            id: "icedchocolate01",
            name: "Iced Chocolate",
            price: 65,
            desc: "A chilled and indulgent iced chocolate drink.",
            img: "images/ic.jpeg",
        },
        {
            id: "darkchoco01",
            name: "Dark Chocolate Frappe",
            price: 69,
            desc: "A rich, frothy dark chocolate frappe.",
            img: "images/dc.jpg",
        },
        {
            id: "caramel01",
            name: "Caramel Frappe",
            price: 69,
            desc: "A sweet and creamy caramel frappe.",
            img: "images/cf.jpg",
        },
        {
            id: "strawberry01",
            name: "Strawberry Frappe",
            price: 69,
            desc: "A refreshing strawberry frappe.",
            img: "images/scc.jpg",
        },
        {
            id: "taro01",
            name: "Taro Frappe",
            price: 69,
            desc: "A smooth and creamy taro frappe.",
            img: "images/taro.jpg",
        },
        {
            id: "mangograham01",
            name: "Mango Graham Frappe",
            price: 99,
            desc: "A tropical mango graham frappe.",
            img: "images/MGFrappe.jpg",
        },
        {
            id: "cookiesandcream01",
            name: "Cookies and Cream Frappe",
            price: 99,
            desc: "A rich and creamy cookies and cream frappe.",
            img: "images/Cookiesandcream.jpg",
        },
        {
            id: "strawberryoreo01",
            name: "Strawberry Oreo Frappe",
            price: 99,
            desc: "A delicious strawberry oreo frappe.",
            img: "images/StrawBOreo.jpg",
        },
        {
            id: "cheesecakefrappe01",
            name: "Cheesecake Frappe",
            price: 69,
            desc: "A smooth and indulgent cheesecake frappe.",
            img: "images/cheesecakef.jpg",
        },
    
            {
                id: "regularfries",
                name: "Regular Fries",
                price: 50,
                desc: "Crispy golden fries served with your choice of dip.",
                img: "images/regularfries.jpg",
            },
            {
                id: "cheesyfries",
                name: "Cheesy Fries",
                price: 79,
                desc: "Golden fries topped with melted cheese.",
                img: "images/cheesyfries.jpg",
            },
            {
                id: "nachos",
                name: "Nachos",
                price: 89,
                desc: "Crispy nachos with cheese and your choice of topping.",
                img: "images/nachoos.jpg",
            },
            {
                id: "cheesytunasandwich",
                name: "Cheesy Tuna Sandwich",
                price: 89,
                desc: "A sandwich filled with creamy cheesy tuna filling.",
                img: "images/cheesytuna.jpg",
            },
            {
                id: "spameggsandwich",
                name: "Spam & Egg Sandwich",
                price: 89,
                desc: "A delicious sandwich with spam and a fried egg.",
                img: "images/spameggsannobg.png",
            },
            {
                id: "barkadameal",
                name: "Barkada Meal",
                price: 279,
                desc: "A hearty meal perfect for sharing with friends.",
                img: "images/barkada.jpg",
            },
            {
                id: "cheesyhungarian",
                name: "Cheesy Hungarian",
                price: 89,
                desc: "Hungarian sausage with cheese and spices.",
                img: "images/cheesyhungarian.jpg",
            },
            {
                id: "baconcheese",
                name: "Bacon & Cheese",
                price: 89,
                desc: "Bacon and cheese served over a bed of rice.",
                img: "images/cheesyricebowl.jpg",
            },
            {
                id: "garlictunaparmesan",
                name: "Garlic Tuna Parmesan",
                price: 109,
                desc: "Tuna in garlic sauce, topped with parmesan cheese.",
                img: "images/garlicTparme.jpg",
            },
            {
                id: "meatyspaghetti",
                name: "Meaty Spaghetti",
                price: 109,
                desc: "Spaghetti pasta served with a meaty tomato sauce.",
                img: "images/meatyspag.jpg",
            },
            {
                id: "garlicparmesan",
                name: "Garlic Parmesan",
                price: 200,
                desc: "Juicy chicken with a garlic parmesan sauce.",
                img: "images/gpchick.jpg",
            },
            {
                id: "teriyaki",
                name: "Teriyaki",
                price: 210,
                desc: "Tender chicken glazed with sweet teriyaki sauce.",
                img: "images/teriyaki.jpg",
            },
            {
                id: "honeybutter",
                name: "Honey Butter",
                price: 220,
                desc: "A sweet honey butter sauce over tender chicken.",
                img: "images/honeybutter.jpg",
            },
            {
                id: "sweetchili",
                name: "Sweet Chili",
                price: 230,
                desc: "Chicken glazed with sweet chili sauce.",
                img: "images/sweetchiliwings.jpg",
            },
            {
                id: "saltedegg",
                name: "Salted Egg",
                price: 240,
                desc: "Crispy chicken with a salted egg coating.",
                img: "images/chicken5.jpg",
            },
            {
                id: "cheesybacon",
                name: "Cheesy Bacon",
                price: 250,
                desc: "Crispy chicken with a cheesy bacon topping.",
                img: "images/cheesybacon.jpg",
            },
            {
                id: "yangneum",
                name: "Yangneum",
                price: 260,
                desc: "Spicy Korean-style chicken with a flavorful sauce.",
                img: "images/yangneum.jpg",
            },
            {
                id: "barbeque",
                name: "Barbeque",
                price: 270,
                desc: "Grilled chicken with smoky barbeque sauce.",
                img: "images/bbq.jpg",
            },
     
  ];
  